// src/App.tsx
import { useState, useEffect, useMemo } from "react";
import AppRouter from "./router";
import { useI18n } from "./locales";

export default function App() {
  const { t, locale, setLocale } = useI18n();
  const [isDark, setIsDark] = useState(true);

  useEffect(() => {
    document.documentElement.classList.toggle("dark", isDark);
  }, [isDark]);

  function toggleTheme() {
    setIsDark(!isDark);
  }

  const sports = useMemo(
    () => [{ key: "football", label: t("sport.football") }],
    [t],
  );

  return (
    <>
      <header className="bg-app-bg px-4 pt-3 relative border-t-2 border-t-accent">
        <div className="max-w-[1200px] mx-auto">
          {/* Top row: logo + toggles */}
          <div className="flex items-center justify-between mb-1">
            <div className="flex items-center gap-2.5">
              <svg className="w-6 h-6 text-[#4fc3f7]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <circle cx="12" cy="12" r="10" />
                <path d="M12 2a14.8 14.8 0 0 1 4 10 14.8 14.8 0 0 1-4 10A14.8 14.8 0 0 1 8 12 14.8 14.8 0 0 1 12 2z" />
                <path d="M2 12h20M2 12a14.8 14.8 0 0 0 4-4M2 12a14.8 14.8 0 0 1 4 4M22 12a14.8 14.8 0 0 1-4-4M22 12a14.8 14.8 0 0 0-4 4" />
              </svg>
              <span className="text-base font-extrabold tracking-[3px] bg-gradient-to-br from-[#4fc3f7] to-[#81d4fa] bg-clip-text text-transparent">
                SCOREREF
              </span>
            </div>
            <div className="flex items-center gap-1.5">
              <button
                onClick={toggleTheme}
                className="text-base text-text-muted hover:text-[#f4c542] px-1.5 py-0.5 rounded transition-colors cursor-pointer"
              >
                {isDark ? "\u2600" : "\u263E"}
              </button>
              <button
                onClick={() => setLocale(locale === "en" ? "zh-CN" : "en")}
                className="text-xs text-text-muted hover:text-accent px-2 py-0.5 rounded transition-colors cursor-pointer"
              >
                {locale === "en" ? "\u4E2D\u6587" : "EN"}
              </button>
            </div>
          </div>

          {/* Sport tabs */}
          <div className="flex gap-0">
            {sports.map((s) => (
              <button
                key={s.key}
                className="text-[13px] font-semibold text-accent pb-2 border-b-2 border-accent h-9 leading-9 cursor-pointer"
              >
                {s.label}
              </button>
            ))}
          </div>
        </div>
      </header>

      <AppRouter />

      <footer className="text-center py-8 px-4 text-[13px] text-text-muted bg-surface mt-10 border-t border-border">
        <div className="max-w-[1200px] mx-auto">
          <p className="text-xs text-text-muted mb-3">
            This system is currently under development. Data accuracy and real-time updates are still being improved.
          </p>
          <p>
            Contact:{" "}
            <a href="mailto:exprify@gmail.com" className="text-accent no-underline hover:underline">
              exprify@gmail.com
            </a>
          </p>
        </div>
      </footer>
    </>
  );
}

// src/App.vue
<script setup lang="ts">
import { ref, computed } from "vue";
import { useI18n } from "./locales";

const { t, locale, setLocale } = useI18n();

const isDark = ref(true);
document.documentElement.classList.add("dark");

function toggleTheme() {
  isDark.value = !isDark.value;
  document.documentElement.classList.toggle("dark", isDark.value);
}

const sports = computed(() => [
  { key: "football", label: t.value("sport.football") },
]);

const activeSport = ref("football");
</script>

<template>
  <div class="banner">
    <div class="banner-content">
      <div class="banner-top">
        <div class="logo">
          <svg class="logo-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="10" />
            <path d="M12 2a14.8 14.8 0 0 1 4 10 14.8 14.8 0 0 1-4 10A14.8 14.8 0 0 1 8 12 14.8 14.8 0 0 1 12 2z" />
            <path d="M2 12h20M2 12a14.8 14.8 0 0 0 4-4M2 12a14.8 14.8 0 0 1 4 4M22 12a14.8 14.8 0 0 1-4-4M22 12a14.8 14.8 0 0 0-4 4" />
          </svg>
          <span class="logo-text">SCOREREF</span>
        </div>
        <div class="banner-actions">
          <span class="theme-toggle" @click="toggleTheme">
            {{ isDark ? '☀' : '☾' }}
          </span>
          <span class="lang-switch" @click="setLocale(locale === 'en' ? 'zh-CN' : 'en')">
            {{ locale === 'en' ? '中文' : 'EN' }}
          </span>
        </div>
      </div>
      <el-tabs v-model="activeSport" class="sport-tabs">
        <el-tab-pane
          v-for="s in sports"
          :key="s.key"
          :label="s.label"
          :name="s.key"
        />
      </el-tabs>
    </div>
  </div>

  <router-view />

  <footer class="footer">
    <div class="footer-content">
      <p class="footer-desc">This system is currently under development. Data accuracy and real-time updates are still being improved.</p>
      <p>Contact: <a href="mailto:exprify@gmail.com">exprify@gmail.com</a></p>
    </div>
  </footer>
</template>

<style>
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #f5f5f5;
  color: #333;
  min-height: 100vh;
  margin: 0;
}

html.dark body {
  background: #0f0f0f;
  color: #e0e0e0;
}

.footer {
  text-align: center;
  padding: 32px 16px 24px;
  font-size: 13px;
  color: #999;
  background: #1a1a1a;
  margin-top: 40px;
  border-top: 1px solid #2a2a2a;
}

.footer-desc {
  margin: 0 0 12px;
  font-size: 12px;
  color: #aaa;
}

html.dark .footer-desc {
  color: #555;
}

.footer a {
  color: #4fc3f7;
  text-decoration: none;
}

.footer a:hover {
  text-decoration: underline;
}

html:not(.dark) .footer {
  background: #e8e8e8;
  border-top-color: #d0d0d0;
  color: #888;
}

html.dark .footer {
  color: #666;
}
</style>

<style scoped>
.banner {
  background: #0f0f0f;
  padding: 12px 16px 0;
  position: relative;
}
.banner::before {
  content: "";
  position: absolute;
  top: 0; left: 0; right: 0;
  height: 2px;
  background: linear-gradient(90deg, #1565C0, #4fc3f7, #1565C0);
}

.banner-content {
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
  display: flex;
  flex-direction: column;
}

.banner-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.logo {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-shrink: 0;
}

.logo-icon {
  width: 24px;
  height: 24px;
  color: #4fc3f7;
}

.logo-text {
  font-size: 16px;
  font-weight: 800;
  letter-spacing: 3px;
  background: linear-gradient(135deg, #4fc3f7, #81d4fa);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.sport-tabs {
  --el-tabs-header-height: 36px;
}

.sport-tabs :deep(.el-tabs__header) {
  margin: 0;
}

.sport-tabs :deep(.el-tabs__item) {
  color: #666;
  font-size: 13px;
  font-weight: 500;
  height: 36px;
  line-height: 36px;
}

.sport-tabs :deep(.el-tabs__item.is-active) {
  color: #4fc3f7;
  font-weight: 600;
}

.sport-tabs :deep(.el-tabs__active-bar) {
  background-color: #4fc3f7;
  height: 2px;
}

.sport-tabs :deep(.el-tabs__nav-wrap::after) {
  background-color: #2a2a2a;
  height: 1px;
}

.banner-actions {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-shrink: 0;
}

.theme-toggle {
  font-size: 16px;
  color: #888;
  cursor: pointer;
  padding: 2px 6px;
  border-radius: 4px;
  transition: all 0.2s;
  line-height: 1;
}

.theme-toggle:hover {
  color: #f4c542;
}

.lang-switch {
  font-size: 12px;
  color: #666;
  cursor: pointer;
  padding: 3px 8px;
  border-radius: 4px;
  transition: all 0.2s;
}

.lang-switch:hover {
  color: #4fc3f7;
}
</style>

<style>
html:not(.dark) .banner {
  background: #f5f5f5;
}
html:not(.dark) .banner::before {
  background: linear-gradient(90deg, #0d8cc4, #4fc3f7, #0d8cc4);
}

html:not(.dark) .logo-text {
  background: linear-gradient(135deg, #0d8cc4, #4fc3f7);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

html:not(.dark) .sport-tabs .el-tabs__item {
  color: #999;
}

html:not(.dark) .sport-tabs .el-tabs__item.is-active {
  color: #0d8cc4;
}

html:not(.dark) .sport-tabs .el-tabs__nav-wrap::after {
  background-color: #e0e0e0;
}

html:not(.dark) .theme-toggle {
  color: #999;
}

html:not(.dark) .theme-toggle:hover {
  color: #f4a700;
}

html:not(.dark) .lang-switch {
  color: #999;
}

html:not(.dark) .lang-switch:hover {
  color: #0d8cc4;
}
</style>
